//this can be gotten from: https://docs.google.com/spreadsheets/d/1QLdUJlZobb2NAktUHtboumURBOHx936hSOpZBlCihm8/edit?usp=sharing
let cc = {
  phone: "Phone",
  bldg: "Building",
  name: "Name",
  hname: "Hours Names",
  city: "City",
  street: "Street",
  open: "isOpen",
  description: "Description",
  residential: "is Residential",
  menus: [
    "menu",
    "Garden Gourmet",
    "Brellas",
    "Serrano's",
    "The Press",
    "Early Bird Breakfast Menu",
    "Boulevard Grill",
    "Za Pizza",
    "Café Spice",
    "Prairie Fire Grill",
    "Sunglower BBQ Co.",
    "Sunflower BBQ Co. Breakfast Menu"
  ]
};

let center = { center: { lat: 38.9559656238095, lng: -95.2513079666667 } };
let fooddata = [
  {
    Name: "Mrs. E's",
    label: "E",
    Description:
      "A staple of KU, Mrs. E's is attached to Lewis Hall on Daisy Hill. It is one of our many residential dining locations throughout campus.",
    Building: "Lewis Hall",
    Disclaimer: "",
    Street: "1532 Engel Rd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-2260",
    "is Residential": true,
    dd: true,
    ms: true,
    cash: true,
    bb: true,
    "Hours Names": "Mrs. E's (Lewis)",
    hours1: "Mon-Thurs: 7:00am-8:00pm",
    hours2: "Fri: 7:00am-7:30pm",
    hours3: "Sat-Sun: 11:00am-7:30pm",
    hours4: "",
    address: "1532 Engel Rd. Lawrence, KS 66045",
    lat: 38.954986,
    lng: -95.25803,
    opens: "11:00am,7:00am,7:00am,7:00am,7:00am,7:00am,11:00am",
    closes: "7:30pm,7:30pm,7:30pm,7:30pm,7:30pm,7:30pm,7:30pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "EKDAHL DINING",
    menu: "",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "South Dining Commons",
    label: "S",
    Description:
      "Shared by Oliver and Downs Halls, South Dining Commons is a brand-new dining center located on campus. It is one of the many residential dining locations on campus.",
    Building: "Oliver and Cora Downs Halls",
    Disclaimer: "",
    Street: "1517 West 18th Street",
    City: "Lawrence, KS 66045",
    Phone: "785-864-4087",
    "is Residential": true,
    dd: true,
    ms: true,
    cash: true,
    bb: true,
    "Hours Names": "South Dining Commons (Oliver/Downs)",
    hours1: "Mon-Thurs: 7:00am-7:30pm",
    hours2: "Fri: 7:00am-7:00pm",
    hours3: "Sat-Sun: 11:00am-7:00pm",
    hours4: "",
    address: "1517 West 18th Street Lawrence, KS 66045",
    lat: 38.950577,
    lng: -95.252491,
    opens: "11:00am,7:00am,7:00am,7:00am,7:00am,7:00am,11:00am",
    closes: "7:00pm,7:00pm,7:00pm,7:00pm,7:00pm,7:00pm,7:00pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "SOUTH DINING COMMONS",
    menu: "",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "North College Café",
    label: "N",
    Description:
      "Located in the recently renovated GSP Hall, North College Café is one of the many residential dining locations located throughout campus.",
    Building: "GSP Hall",
    Disclaimer: "",
    Street: "500 W 11th St.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-3120",
    "is Residential": true,
    dd: true,
    ms: true,
    cash: true,
    bb: true,
    "Hours Names": "North College Café (GSP)",
    hours1: "Mon-Thurs: 7:00am-7:30pm",
    hours2: "Fri: 7:00am-2:30pm",
    hours3: "Sat-Sun: 11:00am-2:30pm",
    hours4: "",
    address: "500 W 11th St. Lawrence, KS 66045",
    lat: 38.9651247,
    lng: -95.2417962,
    opens: "11:00am,7:00am,7:00am,7:00am,7:00am,7:00am,11:00am",
    closes: "2:30pm,7:30pm,7:30pm,7:30pm,7:30pm,2:30pm,2:30pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "NORTH COLLEGE CAFE",
    menu: "",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "The Studio Grill",
    label: "G",
    Description:
      "Located in Hashinger Hall, the Studio Grill is one of the many retail dining locations throughout campus.",
    Building: "Hashinger Hall",
    Disclaimer: "",
    Street: "1632 Engel Rd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-1890",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "The Studio Grill (Hashinger)",
    hours1: "Mon-Fri: 5:00pm-Midnight",
    hours2: "Sat-Sun: 7:30pm-Midnight",
    hours3: "",
    hours4: "",
    address: "1632 Engel Rd. Lawrence, KS 66045",
    lat: 38.9540539,
    lng: -95.2588591,
    opens: "7:30pm,5:00pm,5:00pm,5:00pm,5:00pm,5:00pm,7:30pm",
    closes: "midnight, midnight,midnight,midnight,midnight,midnight,midnight",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "http://issuu.com/kumemorialunion/docs/studio_-_menu_boards_fa16?e=26059554/38391583",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Southside",
    label: "S",
    Description:
      "Located in Oliver Hall, Southside is one of the many retail dining locations throughout campus.",
    Building: "Oliver and Cora Downs Halls",
    Disclaimer: "",
    Street: "1815 Naismith Dr.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-4087",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Southside (Oliver/Downs)",
    hours1: "Mon-Fri: 11:00am-11:00pm",
    hours2: "Sat-Sun: 10:00am-11:00pm",
    hours3: "",
    hours4: "",
    address: "1815 Naismith Dr. Lawrence, KS 66045",
    lat: 38.950577,
    lng: -95.252491,
    opens: "10:00am,11:00am,11:00am,11:00am,11:00am,11:00am,10:00am",
    closes: "11:00pm,11:00pm,11:00pm,11:00pm,11:00pm,11:00pm,11:00pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu: "",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "The Market",
    label: "M",
    Description:
      "Located in the Kansas Union, The Market is one of the many retail dining locations throughout campus.",
    Building: "Kansas Union",
    Disclaimer: "",
    Street: "1301 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-2412",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "The Market (Level 3 Kansas Union)",
    hours1: "Mon-Fri: 8:00am-4:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1301 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.9595782,
    lng: -95.2434651,
    opens: "CLOSED,8:00am,8:00am,8:00am,8:00am,8:00am,CLOSED",
    closes: "CLOSED,4:00pm,4:00pm,4:00pm,4:00pm,4:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "UN MARKET",
    menu: "",
    "Garden Gourmet":
      "https://issuu.com/kumemorialunion/docs/garden_gourmet_menu_fa16?e=26059554/38224471",
    Brellas:
      "https://issuu.com/kumemorialunion/docs/web-ready_brellas_fa16?e=26059554/38193480",
    "Serrano's":
      "https://issuu.com/kumemorialunion/docs/serranos_menu_fa16?e=26059554/38224237",
    "The Press":
      "https://issuu.com/kumemorialunion/docs/panini_menu_fa16?e=26059554/38223962",
    "Early Bird Breakfast Menu":
      "https://issuu.com/kumemorialunion/docs/early_bird_menu_fa16?e=26059554/38223750",
    "Boulevard Grill":
      "https://issuu.com/kumemorialunion/docs/boulevard_grill_menu_fa16?e=26059554/38222092",
    "Za Pizza":
      "http://issuu.com/kumemorialunion/docs/web-ready_za_market_menu_fa16?e=26059554/38193033",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "The Underground",
    label: "U",
    Description:
      "A dining staple, The Underground is located in Wescoe Hall. It is one of our many retail dining centers throughout campus.",
    Building: "Wescoe Hall",
    Disclaimer: "",
    Street: "1445 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-5022",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "The Underground (Wescoe)",
    hours1: "Mon-Fri: 7:30am-4:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1445 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.9574035,
    lng: -95.2477536,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,4:00pm,4:00pm,4:00pm,4:00pm,4:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu: "",
    "Garden Gourmet":
      "https://issuu.com/kumemorialunion/docs/garden_gourmet_menu_fa16?e=26059554/38224471",
    Brellas:
      "https://issuu.com/kumemorialunion/docs/web-ready_brellas_fa16?e=26059554/38193480",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza":
      "https://issuu.com/kumemorialunion/docs/web-ready_za_market_menu_fa16?e=26059554/38193033",
    "Café Spice":
      "https://union.ku.edu/sites/union.drupal.ku.edu/files/docs/menus/CafeSpice_FullMenuBoard.pdf",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Courtside Café",
    label: "C",
    Description:
      "Located in the newly constructed DeBruce Center, the Courtside Café is one of the many retail dining centers throughout campus.",
    Building: "DeBruce Center",
    Disclaimer: "",
    Street: "1647 Naismith Drive",
    City: "Lawrence, KS 66045",
    Phone: "785-864-5694",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Courtside Café (DeBruce Center)",
    hours1: "Mon-Fri: 7:00am-3:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1647 Naismith Drive Lawrence, KS 66045",
    lat: 38.955172,
    lng: -95.252289,
    opens: "CLOSED,7:00am,7:00am,7:00am,7:00am,7:00am,CLOSED",
    closes: "CLOSED,3:00pm,3:00pm,3:00pm,3:00pm,3:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "DEBR COURTSIDE CAFE",
    menu: "",
    "Garden Gourmet": "",
    Brellas:
      "https://issuu.com/kumemorialunion/docs/web-ready_brellas_fa16?e=26059554/38193480",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill":
      "https://issuu.com/kumemorialunion/docs/courtsideprairiefiregrillmenu?e=26059554/38749545",
    "Sunglower BBQ Co.":
      "https://issuu.com/kumemorialunion/docs/courtsidesunflowerbbqmenu?e=26059554/38749790",
    "Sunflower BBQ Co. Breakfast Menu":
      "https://issuu.com/kumemorialunion/docs/courtsidesunflowerbbqbreakfastdigit?e=26059554/38750007",
    "": ""
  },
  {
    Name: "Mortar & Pestle Café",
    label: "M",
    Description:
      "Located in the Pharmacy Building on West Campus, Mortar & Pestle Café is one of the many retail dining centers throughout campus.",
    Building: "Pharmacy Building",
    Disclaimer: "",
    Street: "2010 Becker Dr",
    City: "Lawrence, KS 66045",
    Phone: "785-864-7086",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Mortar & Pestle (Pharmacy)",
    hours1: "Mon-Fri: 11:00am-2:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "2010 Becker Dr Lawrence, KS 66045",
    lat: 38.948523,
    lng: -95.263848,
    opens: "CLOSED,11:00am,11:00am,11:00am,11:00am,11:00am,CLOSED",
    closes: "CLOSED,2:00pm,2:00pm,2:00pm,2:00pm,2:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "PHAR MORTAR &amp; PESTLE",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_freshfusion_menu_boards_fa17?e=26059554/52397010",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "The Bus Stop",
    label: "B",
    Description:
      "Located in the newly constructed Self Hall, the Bus Stop is one of the many retail dining centers throughout campus.",
    Building: "Self Hall",
    Disclaimer: "",
    Street: "1620 Engel Rd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-2991",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "The Bus Stop (Self)",
    hours1: "Mon-Fri: 7:00am-Midnight",
    hours2: "Sat-Sun: 9:00am-Midnight",
    hours3: "",
    hours4: "",
    address: "1620 Engel Rd. Lawrence, KS 66045",
    lat: 38.955373,
    lng: -95.259124,
    opens: "9:00am,7:00am,7:00am,7:00am,7:00am,7:00am,9:00am",
    closes: "midnight,midnight,midnight,midnight,midnight,midnight,midnight",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewcappuci",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Impromptu Café",
    label: "I",
    Description:
      "Located in the Kansas Union, the Impromptu Café offers more of a restaurant-style feel than many of our other locations. It is one of the many residential dining locations throughout campus.",
    Building: "Kansas Union",
    Disclaimer: "",
    Street: "1301 Jayhawk Blvd",
    City: "Lawrence, KS 66045",
    Phone: "785-864-8001",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Impromptu Cafe (Level 3 Kansas Union)",
    hours1: "Mon-Fri: 11:00am-2:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1301 Jayhawk Blvd Lawrence, KS 66045",
    lat: 38.9595782,
    lng: -95.2434651,
    opens: "CLOSED,11:00am,11:00am,11:00am,11:00am,11:00am,CLOSED",
    closes: "CLOSED,2:00pm,2:00pm,2:00pm,2:00pm,2:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/impromptu_web_menu_sp16?e=26059554/38226212",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Engineering Commons Jay Break",
    label: "E",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "LEEP2",
    Disclaimer: "",
    Street: "1536 W. 15th St.",
    City: "Lawrence, KS 66045",
    Phone: "",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Engineering Commons Jay Break (LEEP2)",
    hours1: "Mon-Thurs: 7:30am-8:00pm",
    hours2: "Fri: 7:30am-2:30pm",
    hours3: "Sat-Sun: Closed",
    hours4: "",
    address: "1536 W. 15th St. Lawrence, KS 66045",
    lat: 38.95741719999999,
    lng: -95.2540253,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,8:00pm,8:00pm,8:00pm,8:00pm,2:30pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewcappuci",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "JRP Jay Break",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Joseph R Pearson",
    Disclaimer: "",
    Street: "1122 West Campus Rd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-1076",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "JRP Jay Break (JRP)",
    hours1: "Mon-Thurs: 7:30am-4:30pm",
    hours2: "Fri: 7:30am-2:30pm",
    hours3: "Sat-Sun: Closed",
    hours4: "",
    address: "1122 West Campus Rd. Lawrence, KS 66045",
    lat: 38.9624281,
    lng: -95.2505894,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,4:30pm,4:30pm,4:30pm,4:30pm,2:30pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewnocappu",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Strong Hall Jay Break",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Strong Hall",
    Disclaimer: "",
    Street: "1450 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-8017",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Strong Hall Jay Break (Strong)",
    hours1: "Mon-Fri: 7:30am-2:30pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1450 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.958542,
    lng: -95.2476138,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,2:30pm,2:30pm,2:30pm,2:30pm,2:30pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewnocappu",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Watson Jay Break",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Watson Library",
    Disclaimer: "",
    Street: "1425 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-1937",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Watson Jay Break (Watson)",
    hours1: "Mon-Thurs: 8:00am-4:00pm",
    hours2: "Fri: 8:00am-2:00pm",
    hours3: "Sat-Sun: Closed",
    hours4: "",
    address: "1425 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.9565813,
    lng: -95.24484,
    opens: "CLOSED,8:00am,8:00am,8:00am,8:00am,8:00am,CLOSED",
    closes: "CLOSED,4:00pm,4:00pm,4:00pm,4:00pm,2:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewnocappu",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Anschutz Jay Break",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Anshutz",
    Disclaimer: "",
    Street: "1301 Hoch Auditoria Dr.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-2948",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Anschutz Jay Break (Anschutz)",
    hours1: "Mon-Thurs: 7:00am-11:00pm",
    hours2: "Fri: 7:00am-2:00pm",
    hours3: "Sat-Sun: Closed",
    hours4: "",
    address: "1301 Hoch Auditoria Dr. Lawrence, KS 66045",
    lat: 38.9573285,
    lng: -95.2496611,
    opens: "CLOSED,7:00am,7:00am,7:00am,7:00am,7:00am,CLOSED",
    closes: "CLOSED,11:00pm,11:00pm,11:00pm,11:00pm,2:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewcappuci",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Roasterie",
    label: "R",
    Description:
      "Headquartered in Kansas City, The Roasterie is one of the most renowned speciality coffee roasters in the nation. Stop by one of their many campus locations today!",
    Building: "Kansas Union",
    Disclaimer: "",
    Street: "1301 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-8008",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Union Roasterie (Level 4 Kansas Union)",
    hours1: "Mon-Thurs: 7:30am-7:00pm",
    hours2: "Fri: 7:30am-6:00pm",
    hours3: "Sat: 9:00am-3:00pm",
    hours4: "Sun: Closed",
    address: "1301 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.9595782,
    lng: -95.2434651,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,9:00am",
    closes: "CLOSED,7:00pm,7:00pm,7:00pm,7:00pm,6:00pm,3:00pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/the_roasterie?e=26059554/38796788",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Roasterie",
    label: "R",
    Description:
      "Headquartered in Kansas City, The Roasterie is one of the most renowned speciality coffee roasters in the nation. Stop by one of their many campus locations today!",
    Building: "DeBruce Center",
    Disclaimer: "",
    Street: "1647 Naismith Drive",
    City: "Lawrence, KS 66045",
    Phone: "785-864-5694",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "DeBruce Roasterie (DeBruce Center)",
    hours1: "Mon-Thurs: 7:00am-6:00pm",
    hours2: "Fri: 7:00am-5:00pm",
    hours3: "Sat: 10:00am-3:00pm",
    hours4: "Sun: Closed",
    address: "1647 Naismith Drive Lawrence, KS 66045",
    lat: 38.955172,
    lng: -95.252289,
    opens: "CLOSED,7:00am,7:00am,7:00am,7:00am,7:00am,10:00am",
    closes: "CLOSED,6:00pm,6:00pm,6:00pm,6:00pm,5:00pm,3:00pm",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/the_roasterie?e=26059554/38796788",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Roasterie",
    label: "R",
    Description:
      "Headquartered in Kansas City, The Roasterie is one of the most renowned speciality coffee roasters in the nation. Stop by one of their many campus locations today!",
    Building: "Wescoe Hall",
    Disclaimer: "",
    Street: "1445 Jayhawk Blvd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-2496",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Wescoe Roasterie (Wescoe)",
    hours1: "Mon-Fri: 7:30am-4:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1445 Jayhawk Blvd. Lawrence, KS 66045",
    lat: 38.9574035,
    lng: -95.2477536,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,4:00pm, 4:00pm,4:00pm,4:00pm,4:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/the_roasterie?e=26059554/38796788",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Roasterie",
    label: "R",
    Description:
      "Headquartered in Kansas City, The Roasterie is one of the most renowned speciality coffee roasters in the nation. Stop by one of their many campus locations today!",
    Building: "Pharmacy Building",
    Disclaimer: "",
    Street: "2010 Becker Dr",
    City: "Lawrence, KS 66045",
    Phone: "785-864-7086",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "Pharmacy Roasterie (Pharmacy)",
    hours1: "Mon-Fri: 8:00am-2:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "2010 Becker Dr Lawrence, KS 66045",
    lat: 38.948523,
    lng: -95.263848,
    opens: "CLOSED,8:00am,8:00am,8:00am,8:00am,8:00am,CLOSED",
    closes: "CLOSED,2:00PM,2:00pm,2:00pm,2:00pm,2:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/the_roasterie?e=26059554/38796788",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "J Café",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Capitol Federal Hall",
    Disclaimer: "Not managed by KU Dining",
    Street: "1654 Naismith Dr",
    City: "Lawrence, KS 66045",
    Phone: "",
    "is Residential": false,
    dd: false,
    ms: false,
    cash: true,
    bb: false,
    "Hours Names": "",
    hours1: "Mon-Thu: 7:30am-4:30pm",
    hours2: "​Fri: 7:30am-2:30pm",
    hours3: "Sat-Sun: Closed",
    hours4: "",
    address: "1654 Naismith Dr Lawrence, KS 66045",
    lat: 38.95365,
    lng: -95.24997,
    opens: "CLOSED,7:30am,7:30am,7:30am,7:30am,7:30am,CLOSED",
    closes: "CLOSED,4:30pm,4:30pm,4:30pm,4:30pm,2:30pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu: "",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  },
  {
    Name: "Burge Jay Break",
    label: "J",
    Description:
      "Craving convenient, delicious food but don't have a lot of time? Jay Break has you covered. We bring the food to you! Jay Break offer freshly made sandwiches, salads, breakfast items, snacks and chips. Just grab it and go!",
    Building: "Burge Union",
    Disclaimer: "",
    Street: "1565 Irving Hill Rd.",
    City: "Lawrence, KS 66045",
    Phone: "785-864-0946",
    "is Residential": false,
    dd: true,
    ms: false,
    cash: true,
    bb: true,
    "Hours Names": "",
    hours1: "Mon-Fri: 7:00am-5:00pm",
    hours2: "Sat-Sun: Closed",
    hours3: "",
    hours4: "",
    address: "1565 Irving Hill Rd. Lawrence, KS 66045",
    lat: 38.9559151,
    lng: -95.2535503,
    opens: "CLOSED,7:00am,7:00am,7:00am,7:00am,7:00am,CLOSED",
    closes: "CLOSED,5:00pm,5:00pm,5:00pm,5:00pm,5:00pm,CLOSED",
    netnutrition: "http://netnutrition.union.ku.edu/NetNutrition/7#",
    searchable: "",
    menu:
      "https://issuu.com/kumemorialunion/docs/kuds_jaybreak_menu_posternewcappuci",
    "Garden Gourmet": "",
    Brellas: "",
    "Serrano's": "",
    "The Press": "",
    "Early Bird Breakfast Menu": "",
    "Boulevard Grill": "",
    "Za Pizza": "",
    "Café Spice": "",
    "Prairie Fire Grill": "",
    "Sunglower BBQ Co.": "",
    "Sunflower BBQ Co. Breakfast Menu": "",
    "": ""
  }
];
